### ISSUE TITLE
make coffee taste good

### ISSUE THREAD

**Issue by Madrugaur** [codeRIT/mentorbot#11] opened 2020-11-02 02:48 UTC
^^

**Comment by skyegallup** [comment] 2020-11-02 21:54
I usually put [sugar](https://github.com/chennaione/sugar) in my coffee to make it taste good. Maybe we could try that?

**Comment by skyegallup** [comment] 2021-02-14 19:52
Coffee already tastes decent to me. Closing this issue, since I can't reproduce the bug

**Closed as completed by skyegallup** 2021-02-14 19:52 UTC
Labels: high priority
